# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 10:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20160210_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('mid', models.IntegerField(default=3199602279, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mid',
        ),
        migrations.AddField(
            model_name='person',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='need',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='tc_no',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(b'\\d{11,11}', b'Number must be 11 digits', b'Invalid number')]),
        ),
        migrations.AddField(
            model_name='person',
            name='Charity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.Charity'),
            preserve_default=False,
        ),
    ]
