# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20160220_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='mid',
        ),
        migrations.AddField(
            model_name='charity',
            name='username',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
