# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20160220_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Charity',
            new_name='charity',
        ),
    ]
