# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20160220_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='building',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='no',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='street',
        ),
        migrations.AddField(
            model_name='charity',
            name='address',
            field=models.CharField(default=datetime.datetime(2016, 2, 28, 15, 29, 41, 551126, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charity',
            name='description',
            field=models.CharField(default=datetime.datetime(2016, 2, 28, 15, 29, 49, 158590, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
